name: Docker Images

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: nearzero
            file: Dockerfile
            image: ghcr.io/nearzero-systems/nearzero:test
          - name: monitoring
            file: Dockerfile.monitoring
            image: ghcr.io/nearzero-systems/monitoring:test
          - name: schedule
            file: Dockerfile.schedule
            image: ghcr.io/nearzero-systems/schedule:test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: linux/amd64
          push: false
          tags: ${{ matrix.image }}
