name: autofix.ci

on:
  push:
    branches: [nightly]
  pull_request:
    branches: [nightly]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup biomeJs
        uses: biomejs/setup-biome@a05c02a1304287da45f13648675a70d5841acdbc # v2

      - name: Run Biome formatter
        run:  biome format --write

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
